apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-app
  template:
    metadata:
      labels:
        app: lab-app
    spec:
      containers:
        - name: lab-app
          image: <+artifacts.primary.image>
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: lab-app
spec:
  selector:
    app: lab-app
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
