apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-app
  template:
    metadata:
      labels:
        app: lab-app
    spec:
      containers:
        - name: lab-app
          image: "gilmarsilva1/lab-app:dev"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: lab-app
spec:
  selector:
    app: lab-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
